### ISSUE TITLE
런치 스크린 수정

### ISSUE THREAD

**Issue by dbqls200** [DeveloperAcademy-POSTECH/2024-MacC-A1-2manythinking#120]
## Description
> 설명을 작성하세요.

런치 스크린 디자인이 변경되어 적용할 예정입니다.

</br>

## To-do

- [x] 수정된 런치 스크린 디자인 적용하기
- [ ] 다크 모드 버전 이미지 에셋 추가하기

</br>

## ETC (참고 자료)
> 참고할 수 있는 링크나 문서가 있다면 첨부해주세요.

**Comment by Minkyeong-Choi** [comment]
다크모드 이미지와 온보딩 json 파일은 모두 #124 이곳에 포함되었습니다!
